config/routes.rb
class AdminRequest
  def self.matches?(request)
    # Allow access to all routes in development, and restrict to the
    # internal or external admin host otherwise.
    !Rails.env.production? || valid_admin_host?(request.host)
  end

  def self.valid_admin_host?(host)
    [Whitehall.admin_host, Whitehall.internal_admin_host].include? host
  end
end

Whitehall::Application.routes.draw do
  VALID_LOCALES_REGEX = Regexp.compile(Locale.non_english.map(&:code).join("|"))

  def redirect(path, options = { prefix: Whitehall.router_prefix })
    super(options[:prefix] + path)
  end

  def external_redirect(path_prefix, target)
    get path_prefix => redirect(target, prefix: "")
    get "#{path_prefix}/*anything" => redirect(target, prefix: "")
  end

  root to: redirect("/admin/"), constraints: lambda { |request|
    ::Whitehall.admin_host == request.host
  }

  get "/government/ministers/minister-of-state--11" => redirect("/government/people/kris-hopkins", prefix: "")

  # This API is documented here:
  # https://github.com/alphagov/whitehall/blob/master/docs/api.md
  namespace "api" do
    resources :governments, only: %i[index show], defaults: { format: :json }
    resources :world_locations, path: "world-locations", only: %i[index show], defaults: { format: :json } do
      resources :worldwide_organisations, path: "organisations", only: [:index], defaults: { format: :json }
    end
    resources :worldwide_organisations, path: "worldwide-organisations", only: [:show], defaults: { format: :json }
  end

  # World locations and Worldwide organisations
  get "/world/organisations/:organisation_id/office" => redirect("/world/organisations/%{organisation_id}", prefix: "")
  get "/world/organisations/:organisation_id/about" => redirect("/world/organisations/%{organisation_id}", prefix: "")
  get "/world/organisations/:id(.:locale)", as: "worldwide_organisation", to: "worldwide_organisations#show", constraints: { locale: VALID_LOCALES_REGEX }

  resources :worldwide_organisations, path: "world/organisations", only: [] do
    get "/about/:id(.:locale)", as: "corporate_information_page", to: "corporate_information_pages#show", constraints: { locale: VALID_LOCALES_REGEX }
    # Dummy path for the sake of polymorphic_path: will always be directed above.
    get "/about(.:locale)", as: "about", to: "_#_", constraints: { locale: VALID_LOCALES_REGEX }

    get "/office/:id(.:locale)", to: "worldwide_offices#show", as: :worldwide_office, constraints: { locale: VALID_LOCALES_REGEX }
  end

  resources :embassies, path: "world/embassies", only: [:index]

  get "/world(.:locale)", as: "world_locations", to: "world_locations#index", constraints: { locale: VALID_LOCALES_REGEX }
  get "/world/:id(.:locale)", as: "world_location", to: "world_locations#show", constraints: { locale: VALID_LOCALES_REGEX }
  get "/world/:world_location_id/news(.:locale)", as: "world_location_news_index", to: "world_location_news#index", constraints: { locale: VALID_LOCALES_REGEX }

  scope Whitehall.router_prefix, shallow_path: Whitehall.router_prefix do
    external_redirect "/organisations/ministry-of-defence-police-and-guarding-agency",
      "http://webarchive.nationalarchives.gov.uk/20121212174735/http://www.mod.uk/DefenceInternet/AboutDefence/WhatWeDo/SecurityandIntelligence/MDPGA/"

    root to: redirect("/", prefix: ""), via: :get, as: :main_root
    get "/how-government-works" => "home#how_government_works", as: "how_government_works"
    scope "/get-involved" do
      root to: "home#get_involved", as: :get_involved, via: :get
      get "take-part" => redirect("/get-involved#take-part")

      # Controller removed. Whitehall frontend no longer serves these
      # pages however the route is needed to generate path and url
      # helper methods.
      # TODO: Remove when take part page paths can be otherwise generated
      get "take-part/:id", to: "take_part_pages#show", as: "take_part_page"
    end

    # Past foreign secretaries are currently hard-coded, so this
    # resource falls straight through to views.
    resources :past_foreign_secretaries, path: "/history/past-foreign-secretaries", only: %i[index show]
    # Past chancellors is also hard-coded
    get "history/past-chancellors" => "historic_appointments#past_chancellors"

    # Past foreign secretaries and past chancellors are here for the
    # purposes of reversing URLs in a consistent way from other views.

    # TODO: make these dynamic, they're hard-coded above.
    get "/history/:role" => "historic_appointments#index", constraints: { role: /(past-prime-ministers)|(past-chancellors)|(past-foreign-secretaries)/ }, as: "historic_appointments"
    get "/history/:role/:person_id" => "historic_appointments#show", constraints: { role: /(past-prime-ministers)|(past-chancellors)|(past-foreign-secretaries)/ }, as: "historic_appointment"
    resources :histories, path: "history", only: %i[index show]

    resource :email_signups, path: "email-signup", only: %i[new]
    get "/email-signup", to: redirect("/")

    get "/tour" => redirect("/tour", prefix: "")

    get "/announcements(.:locale)", as: "announcements", to: "announcements#index", constraints: { locale: VALID_LOCALES_REGEX }
    get "/news/:id(.:locale)", as: "news_article", to: "news_articles#show", constraints: { locale: VALID_LOCALES_REGEX }
    resources :fatality_notices, path: "fatalities", only: [:show]
    get "/news" => redirect("/announcements"), as: "news_articles"
    get "/fatalities" => redirect("/announcements"), as: "fatality_notices"

    get "/latest" => "latest#index", as: "latest"

    get "/publications(.:locale)", as: "publications", to: "publications#index", constraints: { locale: VALID_LOCALES_REGEX }
    get "/publications/:id(.:locale)", as: "publication", to: "_#_", constraints: { locale: VALID_LOCALES_REGEX }
    get "/publications/:publication_id/:id" => "_#_", as: "publication_html_attachment"

    # TODO: Remove when paths can be generated without a routes entry
    get "/case-studies/:id(.:locale)", as: "case_study", to: "case_studies#show", constraints: { locale: VALID_LOCALES_REGEX }
    get "/speeches/:id(.:locale)", as: "speech", to: "speeches#show", constraints: { locale: VALID_LOCALES_REGEX }
    resources :statistical_data_sets, path: "statistical-data-sets", only: [:show]

    get "/speeches" => redirect("/announcements")

    # Controller removed for stats announce show. Whitehall frontend no longer serves these
    # pages however the route is needed to generate path and url
    # helper methods.
    # TODO: Remove `:show` when stats announcement paths can be otherwise generated
    resources :statistics_announcements, path: "statistics/announcements", only: %i[index show]
    get "/statistics(.:locale)", as: "statistics", to: "statistics#index", constraints: { locale: VALID_LOCALES_REGEX }
    get "/statistics/:id(.:locale)", as: "statistic", to: "_#_", constraints: { locale: VALID_LOCALES_REGEX }
    get "/world-location-news(.:locale)", as: "world_location_news_articles", to: "world_location_news_articles#index", constraints: { locale: VALID_LOCALES_REGEX }
    get "/world-location-news/:id(.:locale)", as: "world_location_news_article", to: "world_location_news_articles#show", constraints: { locale: VALID_LOCALES_REGEX }

    resources :consultations, only: %i[index show] do
      collection do
        get :open
        get :closed
        get :upcoming
      end
    end
    get "/consultations/:consultation_id/:id" => "_#_", as: "consultation_html_attachment"
    get "/consultations/:consultation_id/outcome/:id" => "_#_", as: "consultation_outcome_html_attachment"
    get "/consultations/:consultation_id/public-feedback/:id" => "_#_", as: "consultation_public_feedback_html_attachment"

    resources :topics, path: "topics", only: [:show]
    resources :topical_events, path: "topical-events", only: [:show] do
      # Controller removed. Whitehall frontend no longer serves these
      # pages however the route is needed to generate path and url
      # helper methods.
      # TODO: Remove when about page paths can be otherwise generated
      resource :about_pages, path: "about", only: [:show]
    end

    # TODO: Remove when paths can be generated without a routes entry
    resources :document_collections, only: [:show], path: "collections"
    get "/collections" => redirect("/publications")

    get "/organisations/:id(.:locale)", as: "organisation", to: "organisations#show", constraints: { locale: VALID_LOCALES_REGEX }
    resources :organisations, only: [:index]

    resources :organisations, only: [] do
      # No need to forward the locale as collections aren't localised.
      get "/series/:slug(.:locale)" => redirect("/collections/%{slug}"), constraints: { locale: VALID_LOCALES_REGEX }
      get "/series(.:locale)" => redirect("/publications"), constraints: { locale: VALID_LOCALES_REGEX }
      get "/about(.:locale)", as: "corporate_information_pages", to: "corporate_information_pages#index", constraints: { locale: VALID_LOCALES_REGEX }
      get "/about/:id(.:locale)", as: "corporate_information_page", to: "corporate_information_pages#show", constraints: { locale: VALID_LOCALES_REGEX }
    end
    get "/organisations/:organisation_id/groups" => redirect("/organisations/%{organisation_id}")
    get "/organisations/:organisation_id/groups/:id" => redirect("/organisations/%{organisation_id}")
    get "/organisations/:organisation_id/consultations" => redirect("/organisations/%{organisation_id}")
    get "/organisations/:organisation_id/chiefs-of-staff" => redirect("/organisations/%{organisation_id}")
    get "/organisations/:organisation_slug/email-signup" => "email_signup_information#show",
      as: :organisation_email_signup_information

    get "/ministers(.:locale)", as: "ministerial_roles", to: "ministerial_roles#index", constraints: { locale: VALID_LOCALES_REGEX }

app/models/edition/worldwide_organisations.rb
module Edition::WorldwideOrganisations
  extend ActiveSupport::Concern

  class Trait < Edition::Traits::Trait
    def process_associations_before_save(edition)
      @edition.edition_worldwide_organisations.each do |association|
        edition.edition_worldwide_organisations.build(association.attributes.except("id"))
      end
    end
  end

  included do
    has_many :edition_worldwide_organisations, foreign_key: :edition_id, inverse_of: :edition, dependent: :destroy
    has_many :worldwide_organisations, through: :edition_worldwide_organisations

    validate :at_least_one_worldwide_organisations

    add_trait Trait
  end

  def can_be_associated_with_worldwide_organisations?
    true
  end

  def skip_worldwide_organisations_validation?
    true
  end

  def at_least_one_worldwide_organisations
    unless skip_worldwide_organisations_validation?
      if worldwide_organisations.empty?
        self.errors.add(:worldwide_organisations, "at least one required")
      end
    end
  end
end

app/controllers/admin/worldwide_organisations_controller.rb
class Admin::WorldwideOrganisationsController < Admin::BaseController
  respond_to :html

  before_action :find_worldwide_organisation, except: %i[index new create]

  def index
    respond_with @worldwide_organisations = WorldwideOrganisation.ordered_by_name
  end

  def new
    @worldwide_organisation = WorldwideOrganisation.new
    @worldwide_organisation.build_default_news_image
    respond_with :admin, @worldwide_organisation
  end

  def create
    @worldwide_organisation = WorldwideOrganisation.create(worldwide_organisation_params)
    respond_with :admin, @worldwide_organisation
  end

  def edit
    @worldwide_organisation.build_default_news_image
    respond_with :admin, @worldwide_organisation
  end

  def update
    @worldwide_organisation.update_attributes(worldwide_organisation_params)
    respond_with :admin, @worldwide_organisation
  end

  def show; end

  def access_info
    @access_and_opening_times = @worldwide_organisation.access_and_opening_times ||
      @worldwide_organisation.build_access_and_opening_times
  end

  def set_main_office
    org_params = params.require(:worldwide_organisation).permit(:main_office_id)
    if @worldwide_organisation.update_attributes(org_params)
      flash[:notice] = "Main office updated successfully"
    end
    respond_with :admin, @worldwide_organisation, WorldwideOffice
  end

  def destroy
    @worldwide_organisation.destroy
    respond_with :admin, @worldwide_organisation
  end

private

  def find_worldwide_organisation
    @worldwide_organisation = WorldwideOrganisation.friendly.find(params[:id])
  end

  def worldwide_organisation_params
    params.require(:worldwide_organisation).permit(
      :name, :logo_formatted_name,
      world_location_ids: [],
      sponsoring_organisation_ids: [],
      default_news_image_attributes: %i[file file_cache]
    )
  end
end

app/controllers/api/worldwide_organisations_controller.rb
class Api::WorldwideOrganisationsController < PublicFacingController
  skip_before_action :set_cache_control_headers
  skip_before_action :restrict_request_formats
  before_action :set_api_cache_control_headers
  before_action :set_api_access_control_allow_origin_headers
  respond_to :json

  self.responder = Api::Responder

  def show
    @worldwide_organisation = WorldwideOrganisation.friendly.find(params[:id])
    if @worldwide_organisation
      respond_with Api::WorldwideOrganisationPresenter.new(@worldwide_organisation, view_context)
    else
      respond_with_not_found
    end
  end

  def index
    if world_location
      respond_with Api::WorldwideOrganisationPresenter.paginate(
        world_location.worldwide_organisations,
        view_context,
      )
    else
      respond_with_not_found
    end
  end

private

  def respond_with_not_found
    respond_with Hash.new, status: :not_found
  end

  def world_location
    @world_location ||= WorldLocation.find_by(slug: params[:world_location_id])
  end
end

app/controllers/worldwide_organisations_controller.rb
class WorldwideOrganisationsController < PublicFacingController
  include CacheControlHelper
  include PermissionsChecker

  enable_request_formats show: :json
  before_action :load_worldwide_organisation

  respond_to :html, :json

  def show
    respond_to do |format|
      format.html do
        set_expiry 5.minutes
        @world_locations = @worldwide_organisation.world_locations
        @main_office = @worldwide_organisation.main_office if @worldwide_organisation.main_office
        @home_page_offices = @worldwide_organisation.home_page_offices
        @primary_role = primary_role
        @other_roles = ([secondary_role] + office_roles).compact
        set_meta_description(@worldwide_organisation.summary)
        set_slimmer_organisations_header([@worldwide_organisation] + @worldwide_organisation.sponsoring_organisations)
        set_slimmer_world_locations_header(@world_locations)
      end
      format.json { redirect_to api_worldwide_organisation_path(@worldwide_organisation, format: :json) }
    end
  end

private

  def preview?
    params[:preview]
  end

  def current_user_can_preview?
    preview? && user_signed_in?
  end

  def load_worldwide_organisation
    @worldwide_organisation = WorldwideOrganisation.with_translations(I18n.locale).find(params[:id])

    if current_user_can_preview?
      expires_now
      @draft = true
    end
  end

  def primary_role
    RolePresenter.new(@worldwide_organisation.primary_role, view_context) if @worldwide_organisation.primary_role
  end

  def secondary_role
    RolePresenter.new(@worldwide_organisation.secondary_role, view_context) if @worldwide_organisation.secondary_role
  end

  def office_roles
    @worldwide_organisation.office_staff_roles.map { |office_staff| RolePresenter.new(office_staff, view_context) }
  end
end

app/helpers/admin/worldwide_organisations_helper.rb
module Admin::WorldwideOrganisationsHelper
  def worldwide_organisation_tabs(worldwide_organisation)
    {
      "Details" => admin_worldwide_organisation_path(worldwide_organisation),
      "Translations" => admin_worldwide_organisation_translations_path(worldwide_organisation),
      "Offices" => admin_worldwide_organisation_worldwide_offices_path(worldwide_organisation),
      "Access and opening times" => access_info_admin_worldwide_organisation_path(worldwide_organisation),
      "Social media accounts" => admin_worldwide_organisation_social_media_accounts_path(worldwide_organisation),
      "Corporate information pages" => admin_worldwide_organisation_corporate_information_pages_path(worldwide_organisation),
    }
  end

  def worldwide_office_shown_on_home_page_text(worldwide_organisation, worldwide_office)
    if worldwide_organisation.is_main_office?(worldwide_office)
      "Yes (as main office)"
    elsif worldwide_organisation.office_shown_on_home_page?(worldwide_office)
      "Yes"
    else
      "No"
    end
  end
end

app/views/worldwide_organisations/_corporate_information.html.erb
<section class="corporate-information" id="corporate-info">
  <div class="inner-block">
    <h1 class="keyline-header"><%= t('worldwide_organisation.headings.corporate_information') %></h1>

    <div class="corporate-information-block">
      <nav class="group sub_navigation" role="navigation">
        <ul>
          <% organisation.corporate_information_pages.published.by_menu_heading(:our_information).each do |corporate_information_page| %>
            <% corporate_information_page.extend(UseSlugAsParam) %>
            <li <%= corporate_information_page.title_lang %> ><%= link_to corporate_information_page.title, [organisation, corporate_information_page] %></li>
          <% end %>

          <% organisation.corporate_information_pages.published.by_menu_heading(:jobs_and_contracts).each do |corporate_information_page| %>
            <% corporate_information_page.extend(UseSlugAsParam) %>
            <li <%= corporate_information_page.title_lang %> ><%= link_to corporate_information_page.title, [organisation, corporate_information_page]%></li>
          <% end %>
        </ul>
      </nav>
    </div>
    <p class="information">
      <% if organisation.corporate_information_pages.published.for_slug("publication-scheme").present? %>
        <%= t('worldwide_organisation.corporate_information.publication_scheme_html',
              link: t_corporate_information_page_link(organisation, "publication-scheme")) %>
      <% end %>
      <% if organisation.corporate_information_pages.published.for_slug("welsh-language-scheme").present? %>
        <%= t('worldwide_organisation.corporate_information.welsh_language_scheme_html',
              link: t_corporate_information_page_link(organisation, "welsh-language-scheme")) %>
      <% end %>
      <% if organisation.corporate_information_pages.published.for_slug("personal-information-charter").present? %>
        <%= t('worldwide_organisation.corporate_information.personal_information_charter_html',
              link: t_corporate_information_page_link(organisation, "personal-information-charter")) %>
      <% end %>
    </p>
  </div>
</section>

app/views/worldwide_organisations/_header.html.erb
<%
  world_locations ||= organisation.world_locations
  link_to_organisation ||= false
  object_for_translation ||= organisation
%>
<header class="block worldwide-organisation-header">
  <div class="inner-block floated-children">
    <div class="logo">
      <%= render "govuk_publishing_components/components/organisation_logo", {
        organisation: {
          name: organisation_logo_name(organisation),
          url: link_to_organisation ? worldwide_organisation_path(organisation) : nil,
          crest: "single-identity",
        }
      } %>
    </div>

    <div class="headings-block">
      <%= render partial: 'shared/available_languages', locals: { object: object_for_translation } %>
    </div>

    <div class="metadata">
      <dl>
        <% if world_locations.any? %>
          <dt><%= t('worldwide_organisation.location') %>:</dt>
          <dd class="js-hide-other-links"><%= world_locations.map {|l| link_to(l.name, l) }.to_sentence.html_safe %></dd>
        <% end %>
        <dt><%= t('worldwide_organisation.part_of') %>:</dt>
        <dd><%= organisation.sponsoring_organisations.map {|o| link_to(o.name, o, class: "sponsoring-organisation") }.to_sentence.html_safe %></dd>
      </dl>
    </div>
  </div>
</header>

app/views/worldwide_organisations/_worldwide_organisation.html.erb
<%= content_tag_for(:div, worldwide_organisation, :class => 'worldwide-organisation') do %>
  <div class="worldwide-organisation-detail">
    <div class="content">
      <% worldwide_organisation.sponsoring_organisations.each do |organisation| %>
        <div class="organisation sponsoring-organisation">
          <span class="<%= logo_classes(class_name: 'single-identity', size: 'medium', stacked: false) %>">
            <%= organisation.name %>
          </span>
        </div>
      <% end %>
      <h2 class="name"><%= link_to worldwide_organisation.name, worldwide_organisation %></h2>
      <p><%= worldwide_organisation.summary %></p>
      <p><%= link_to t('worldwide_organisation.find_out_more'), worldwide_organisation %></p>
    </div>
  </div>

  <%= render('contacts/contact', contact: worldwide_organisation.main_office) if worldwide_organisation.main_office.present? %>
<% end %>

app/views/worldwide_organisations/show.html.erb
<% page_title @worldwide_organisation.name %>
<% page_class "worldwide-organisations-show" %>

<%= render partial: 'header', locals: { organisation: @worldwide_organisation, world_locations: @world_locations } %>

<section class="block about-block" id="about-us">
  <div class="inner-block floated-children">
    <div class="about-us">
      <div class="content">
        <p class="summary"><%= @worldwide_organisation.summary %></p>
        <div class="description">
          <% if @draft %>
          <%= govspeak_edition_to_html @worldwide_organisation.draft_about_us %>
          <% else %>
          <%= govspeak_edition_to_html @worldwide_organisation.about_us %>
          <% end %>
        </div>
      </div>
    </div>
    <% if @worldwide_organisation.social_media_accounts.any? %>
      <aside class="social-media-links">
        <div class="content">
          <h1><%= t('worldwide_organisation.headings.follow_us') %></h1>
            <%= render 'shared/social_media_accounts', socialable: @worldwide_organisation, followus: true %>
        </div>
      </aside>
    <% end %>
  </div>
</section>

<% if ([@primary_role]+@other_roles).compact.any?(&:has_appointment?) %>
  <section class="block people" id="people">
    <div class="inner-block floated-children">
      <h1 class="keyline-header"><%= t('worldwide_organisation.headings.our_people' ) %></h1>
      <%= render( partial: 'people/person',
                  locals: {
                    person: @primary_role.current_person,
                    roles: [@primary_role],
                    hlevel: 'h2',
                    wrapping_element: :div }) if @primary_role %>
      <ul class="people-list">
        <% clear_person = 0 %>
        <% @other_roles.each do |role| %>
          <%= render( partial: 'people/person',
                      locals: {
                        person: role.current_person,
                        roles: [role],
                        hlevel: 'h2',
                        hide_image: true,
                        extra_class: ((clear_person += 1) % 3 == 1 ? 'clear-person' : '')}) %>
        <% end %>
      </ul>
    </div>
  </section>
<% end %>

<% if @main_office %>
  <section class="block contact-us" id="contact-us">
    <div class="inner-block floated-children">
      <h1 class="keyline-header"><%= t('worldwide_organisation.headings.contact_us' ) %></h1>
      <%= render partial: 'contacts/contact', locals: {contact: @main_office, is_main: true, lang: t_lang_translated_locales(@main_office.contact) } %>

      <% @home_page_offices.each do |home_page_office| %>
        <%= render partial: 'contacts/contact', locals: { contact: home_page_office, lang:  t_lang_translated_locales(home_page_office.contact) } %>
      <% end %>
    </div>
  </section>
<% end %>

<% if @worldwide_organisation.corporate_information_pages.any? %>
  <%= render partial: 'corporate_information', locals: { organisation: @worldwide_organisation } %>
<% end %>