config/routes.rb
class AdminRequest
  def self.matches?(request)
    # Allow access to all routes in development, and restrict to the
    # internal or external admin host otherwise.
    !Rails.env.production? || valid_admin_host?(request.host)
  end

  def self.valid_admin_host?(host)
    [Whitehall.admin_host, Whitehall.internal_admin_host].include? host
  end
end

Whitehall::Application.routes.draw do
  VALID_LOCALES_REGEX = Regexp.compile(Locale.non_english.map(&:code).join("|"))

  def redirect(path, options = { prefix: Whitehall.router_prefix })
    super(options[:prefix] + path)
  end

  def external_redirect(path_prefix, target)
    get path_prefix => redirect(target, prefix: "")
    get "#{path_prefix}/*anything" => redirect(target, prefix: "")
  end

  root to: redirect("/admin/"), constraints: lambda { |request|
    ::Whitehall.admin_host == request.host
  }

  get "/government/ministers/minister-of-state--11" => redirect("/government/people/kris-hopkins", prefix: "")

  # This API is documented here:
  # https://github.com/alphagov/whitehall/blob/master/docs/api.md
  namespace "api" do
    resources :governments, only: %i[index show], defaults: { format: :json }
    resources :world_locations, path: "world-locations", only: %i[index show], defaults: { format: :json } do
      resources :worldwide_organisations, path: "organisations", only: [:index], defaults: { format: :json }
    end
    resources :worldwide_organisations, path: "worldwide-organisations", only: [:show], defaults: { format: :json }
  end

  # World locations and Worldwide organisations
  get "/world/organisations/:organisation_id/office" => redirect("/world/organisations/%{organisation_id}", prefix: "")
  get "/world/organisations/:organisation_id/about" => redirect("/world/organisations/%{organisation_id}", prefix: "")
  get "/world/organisations/:id(.:locale)", as: "worldwide_organisation", to: "worldwide_organisations#show", constraints: { locale: VALID_LOCALES_REGEX }

  resources :worldwide_organisations, path: "world/organisations", only: [] do
    get "/about/:id(.:locale)", as: "corporate_information_page", to: "corporate_information_pages#show", constraints: { locale: VALID_LOCALES_REGEX }
    # Dummy path for the sake of polymorphic_path: will always be directed above.
    get "/about(.:locale)", as: "about", to: "_#_", constraints: { locale: VALID_LOCALES_REGEX }

    get "/office/:id(.:locale)", to: "worldwide_offices#show", as: :worldwide_office, constraints: { locale: VALID_LOCALES_REGEX }
  end

  resources :embassies, path: "world/embassies", only: [:index]

  get "/world(.:locale)", as: "world_locations", to: "world_locations#index", constraints: { locale: VALID_LOCALES_REGEX }
  get "/world/:id(.:locale)", as: "world_location", to: "world_locations#show", constraints: { locale: VALID_LOCALES_REGEX }
  get "/world/:world_location_id/news(.:locale)", as: "world_location_news_index", to: "world_location_news#index", constraints: { locale: VALID_LOCALES_REGEX }

  scope Whitehall.router_prefix, shallow_path: Whitehall.router_prefix do
    external_redirect "/organisations/ministry-of-defence-police-and-guarding-agency",
      "http://webarchive.nationalarchives.gov.uk/20121212174735/http://www.mod.uk/DefenceInternet/AboutDefence/WhatWeDo/SecurityandIntelligence/MDPGA/"

    root to: redirect("/", prefix: ""), via: :get, as: :main_root
    get "/how-government-works" => "home#how_government_works", as: "how_government_works"
    scope "/get-involved" do
      root to: "home#get_involved", as: :get_involved, via: :get
      get "take-part" => redirect("/get-involved#take-part")

      # Controller removed. Whitehall frontend no longer serves these
      # pages however the route is needed to generate path and url
      # helper methods.
      # TODO: Remove when take part page paths can be otherwise generated
      get "take-part/:id", to: "take_part_pages#show", as: "take_part_page"
    end

    # Past foreign secretaries are currently hard-coded, so this
    # resource falls straight through to views.
    resources :past_foreign_secretaries, path: "/history/past-foreign-secretaries", only: %i[index show]
    # Past chancellors is also hard-coded
    get "history/past-chancellors" => "historic_appointments#past_chancellors"

    # Past foreign secretaries and past chancellors are here for the
    # purposes of reversing URLs in a consistent way from other views.

    # TODO: make these dynamic, they're hard-coded above.
    get "/history/:role" => "historic_appointments#index", constraints: { role: /(past-prime-ministers)|(past-chancellors)|(past-foreign-secretaries)/ }, as: "historic_appointments"
    get "/history/:role/:person_id" => "historic_appointments#show", constraints: { role: /(past-prime-ministers)|(past-chancellors)|(past-foreign-secretaries)/ }, as: "historic_appointment"
    resources :histories, path: "history", only: %i[index show]

    resource :email_signups, path: "email-signup", only: %i[new]
    get "/email-signup", to: redirect("/")

    get "/tour" => redirect("/tour", prefix: "")

    get "/announcements(.:locale)", as: "announcements", to: "announcements#index", constraints: { locale: VALID_LOCALES_REGEX }
    get "/news/:id(.:locale)", as: "news_article", to: "news_articles#show", constraints: { locale: VALID_LOCALES_REGEX }
    resources :fatality_notices, path: "fatalities", only: [:show]
    get "/news" => redirect("/announcements"), as: "news_articles"
    get "/fatalities" => redirect("/announcements"), as: "fatality_notices"

    get "/latest" => "latest#index", as: "latest"

    get "/publications(.:locale)", as: "publications", to: "publications#index", constraints: { locale: VALID_LOCALES_REGEX }
    get "/publications/:id(.:locale)", as: "publication", to: "_#_", constraints: { locale: VALID_LOCALES_REGEX }
    get "/publications/:publication_id/:id" => "_#_", as: "publication_html_attachment"

    # TODO: Remove when paths can be generated without a routes entry
    get "/case-studies/:id(.:locale)", as: "case_study", to: "case_studies#show", constraints: { locale: VALID_LOCALES_REGEX }
    get "/speeches/:id(.:locale)", as: "speech", to: "speeches#show", constraints: { locale: VALID_LOCALES_REGEX }
    resources :statistical_data_sets, path: "statistical-data-sets", only: [:show]

    get "/speeches" => redirect("/announcements")

    # Controller removed for stats announce show. Whitehall frontend no longer serves these
    # pages however the route is needed to generate path and url
    # helper methods.
    # TODO: Remove `:show` when stats announcement paths can be otherwise generated
    resources :statistics_announcements, path: "statistics/announcements", only: %i[index show]
    get "/statistics(.:locale)", as: "statistics", to: "statistics#index", constraints: { locale: VALID_LOCALES_REGEX }
    get "/statistics/:id(.:locale)", as: "statistic", to: "_#_", constraints: { locale: VALID_LOCALES_REGEX }
    get "/world-location-news(.:locale)", as: "world_location_news_articles", to: "world_location_news_articles#index", constraints: { locale: VALID_LOCALES_REGEX }
    get "/world-location-news/:id(.:locale)", as: "world_location_news_article", to: "world_location_news_articles#show", constraints: { locale: VALID_LOCALES_REGEX }

    resources :consultations, only: %i[index show] do
      collection do
        get :open
        get :closed
        get :upcoming
      end
    end
    get "/consultations/:consultation_id/:id" => "_#_", as: "consultation_html_attachment"
    get "/consultations/:consultation_id/outcome/:id" => "_#_", as: "consultation_outcome_html_attachment"
    get "/consultations/:consultation_id/public-feedback/:id" => "_#_", as: "consultation_public_feedback_html_attachment"

    resources :topics, path: "topics", only: [:show]
    resources :topical_events, path: "topical-events", only: [:show] do
      # Controller removed. Whitehall frontend no longer serves these
      # pages however the route is needed to generate path and url
      # helper methods.
      # TODO: Remove when about page paths can be otherwise generated
      resource :about_pages, path: "about", only: [:show]
    end

    # TODO: Remove when paths can be generated without a routes entry
    resources :document_collections, only: [:show], path: "collections"
    get "/collections" => redirect("/publications")

    get "/organisations/:id(.:locale)", as: "organisation", to: "organisations#show", constraints: { locale: VALID_LOCALES_REGEX }
    resources :organisations, only: [:index]

    resources :organisations, only: [] do
      # No need to forward the locale as collections aren't localised.
      get "/series/:slug(.:locale)" => redirect("/collections/%{slug}"), constraints: { locale: VALID_LOCALES_REGEX }
      get "/series(.:locale)" => redirect("/publications"), constraints: { locale: VALID_LOCALES_REGEX }
      get "/about(.:locale)", as: "corporate_information_pages", to: "corporate_information_pages#index", constraints: { locale: VALID_LOCALES_REGEX }
      get "/about/:id(.:locale)", as: "corporate_information_page", to: "corporate_information_pages#show", constraints: { locale: VALID_LOCALES_REGEX }
    end
    get "/organisations/:organisation_id/groups" => redirect("/organisations/%{organisation_id}")
    get "/organisations/:organisation_id/groups/:id" => redirect("/organisations/%{organisation_id}")
    get "/organisations/:organisation_id/consultations" => redirect("/organisations/%{organisation_id}")
    get "/organisations/:organisation_id/chiefs-of-staff" => redirect("/organisations/%{organisation_id}")
    get "/organisations/:organisation_slug/email-signup" => "email_signup_information#show",
      as: :organisation_email_signup_information

    get "/ministers(.:locale)", as: "ministerial_roles", to: "ministerial_roles#index", constraints: { locale: VALID_LOCALES_REGEX }

app/models/feature_list.rb
class FeatureList < ApplicationRecord
  has_many :features, -> { order(:ordering) }, dependent: :destroy, before_add: :ensure_ordering!
  belongs_to :featurable, polymorphic: true

  validates_presence_of :locale
  validates_uniqueness_of :locale, scope: %i[featurable_id featurable_type]

  accepts_nested_attributes_for :features

  def to_s
    "#{featurable.name} (#{locale})"
  end

  def reorder!(new_ordering)
    Feature.connection.transaction do
      start_at = next_ordering
      new_ordering.each.with_index do |feature_id, i|
        feature = self.features.find(feature_id)
        feature.ordering = start_at + i
        feature.save!
      end
    end
    true
  rescue ActiveRecord::RecordNotFound => e
    self.errors[:base] << "Can't reorder because '#{e}'"
    false
  rescue ActiveRecord::RecordInvalid => e
    self.errors[:base] << "Can't reorder because '#{e}' on '#{e.record}'"
    false
  end

  def current
    features.current.includes([:topical_event, { document: :published_edition }])
  end

  def published_features
    features.current.with_published_edition
  end

  def topical_events
    features.current.with_topical_events
  end

  def empty?
    current.empty?
  end

private

  def next_ordering
    (features.map(&:ordering).max || 0) + 1
  end

  def ensure_ordering!(new_feature)
    new_feature.ordering = next_ordering unless new_feature.ordering
  end
end

app/controllers/admin/feature_lists_controller.rb
class Admin::FeatureListsController < Admin::BaseController
  before_action :find_feature_list

  def show
    redirect_to feature_list_path(@feature_list)
  end

  def reorder
    new_order = ordering_params.to_h.sort_by { |_k, v| v.to_i }.map(&:first)
    message = if @feature_list.reorder!(new_order)
                { notice: "Feature order updated" }
              else
                { alert: "Unable to reorder features because #{@feature_list.errors.full_messages.to_sentence}" }
              end
    redirect_to feature_list_path(@feature_list), message
  end

private

  def ordering_params
    # keys in ordering should be the ids of objects so that means they should be
    # integers, we can't permit them based on an allow list, but we can pick
    # only those keys that are integers and permit the whole param object after
    # that
    params.fetch(:ordering, {}).select { |k, _v| k =~ /\A\d+\Z/ }.permit!
  end

  def find_feature_list
    @feature_list = FeatureList.find(params[:id] || params[:feature_list_id])
  end

  def feature_list_path(feature_list)
    polymorphic_url([:features, :admin, feature_list.featurable], locale: feature_list.locale)
  end
end

app/views/admin/feature_lists/_current_feature_list.html.erb
<h2>Currently featured</h2>
<p class="warning">
  Warning: changes to features appear instantly on the live site.
</p>

<% if feature_list.features.current.any? %>
  <% if feature_list.features.current.many? %>
    <p>
      To change the order of your featured documents, drag them up or down and then click "Save ordering".
    </p>
  <% end %>
  <%= form_for feature_list, url: reorder_admin_feature_list_path(feature_list), method: :post do |form| %>
    <fieldset class="sortable">
      <% feature_list.features.current.each do |feature| %>
        <div class="well feature-list">
          <%= label_tag "ordering-#{feature.id}" do %>
            <div class="row">
              <% if feature.document && feature.document.published_edition %>
                <div class="title col-md-6">
                  <i class="glyphicon glyphicon-align-justify add-right-margin"></i>
                  <%= link_to(feature, admin_edition_path(feature.document.published_edition)) %>
                </div>
                <div class="type col-md-2"><%= feature.document.published_edition.type.titleize %> (document)</div>
                <div class="date col-md-2"><%=localize feature.document.published_edition.major_change_published_at.to_date %></div>
                <%= content_tag_for :div, feature.document.published_edition, class: "button text-right col-md-2" do %>
                  <%= link_to('Unfeature',
                        unfeature_admin_feature_list_feature_path(feature_list, feature),
                        data: { confirm: "Unfeature '#{feature}'?" },
                        method: :post,
                        class: "btn btn-danger") %>
                <% end %>
              <% elsif feature.topical_event %>
                <div class="title col-md-6">
                  <i class="glyphicon glyphicon-align-justify add-right-margin"></i>
                  <%= link_to feature.topical_event, edit_admin_topical_event_path(feature.topical_event) %>
                </div>
                <div class="type col-md-2">Topical Event</div>
                <div class="date col-md-2"><%= topical_event_dates_string(feature.topical_event) %></div>
                <%= content_tag_for :div, feature.topical_event, class: "button text-right col-md-2" do %>
                  <%= link_to('Unfeature',
                        unfeature_admin_feature_list_feature_path(feature_list, feature),
                        data: { confirm: "Unfeature '#{feature}'?" },
                        method: :post,
                        class: "btn btn-danger") %>
                <% end %>
              <% elsif feature.offsite_link %>
                <div class="title col-md-6">
                  <i class="glyphicon glyphicon-align-justify add-right-margin"></i>
                  <%= link_to feature.offsite_link, polymorphic_path([:edit, :admin, feature.offsite_link.parent, feature.offsite_link]) %>
                </div>
                <div class="type col-md-2"><%= feature.offsite_link.humanized_link_type %> (offsite link)</div>
                <div class="date col-md-2"><%=localize feature.offsite_link.date.to_date if feature.offsite_link.date %></div>
                <%= content_tag_for :div, feature.offsite_link, class: "button text-right col-md-2" do %>
                  <%= link_to('Unfeature',
                        unfeature_admin_feature_list_feature_path(feature_list, feature),
                        data: { confirm: "Unfeature '#{feature}'?" },
                        method: :post,
                        class: "btn btn-danger") %>
                <% end %>
              <% else %>
                <div class="col-md-6">
                  <i class="glyphicon glyphicon-align-justify add-right-margin"></i>
                  <%= feature.document ? feature.document.latest_edition : "No edition" %>
                </div>
              <% end %>
            </div>
          <% end %>
          <%= text_field_tag "ordering[#{feature.id}]", feature.ordering, id: "ordering-#{feature.id}", class: "ordering" %>
        </div>
      <% end %>
    </fieldset>
    <%= form.submit "Save ordering", class: "btn btn-primary btn-lg" %>
  <% end %>
<% else %>
  <p>Nothing featured yet</p>
<% end %>

app/views/admin/feature_lists/_featurable_editions.html.erb
<% if featurable_editions.present? %>
  <table class="table table-striped table-bordered">
    <thead>
      <tr class="table-header">
        <th>Type</th>
        <th>Title</th>
        <th>Published</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% featurable_editions.each do |edition| %>
        <% edition = LocalisedModel.new(edition, feature_list.locale) %>
        <% next if feature_list.features.current.detect {|f| f.document == edition.document } %>
        <%= content_tag_for :tr, edition do %>
          <td class="type"><%= edition.type.titleize %></td>
          <td><%= link_to edition.title, admin_edition_path(edition) %></td>
          <td><%=localize edition.major_change_published_at.to_date %></td>
          <td>
            <%= link_to("Feature", polymorphic_url([:new, :admin, @feature_list, :feature], edition_id: edition), class: 'btn btn-default') %>
          </td>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <%= paginate featurable_editions, theme: 'twitter-bootstrap-3' %>
<% else %>
  <div class="no-content no-content-bordered">
    No documents found
  </div>
<% end %>

app/views/admin/feature_lists/_featurable_offsite_links.html.erb
<table class="table table-bordered">
  <thead>
    <tr class="table-header">
      <th>Title</th>
      <th>Type</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% featurable_offsite_links.each do |offsite_link| %>
    <% next if feature_list.features.current.detect {|f| f.offsite_link == offsite_link } %>
    <%= content_tag_for :tr, offsite_link do %>
      <td><%= link_to offsite_link.title, polymorphic_path([:edit, :admin, offsite_link.parent, offsite_link]) %></td>
      <td><%= offsite_link.humanized_link_type %></td>
      <td>
        <%= link_to("Feature", polymorphic_url([:new, :admin, @feature_list, :feature], offsite_link_id: offsite_link.id), class: 'btn btn-default') %>
      </td>
      <td>
        <%= button_to("Delete", polymorphic_url([:admin, offsite_link.parent, offsite_link]),
            method: :delete,
            class: "btn btn-danger",
            data: { confirm: "Are you sure you want to delete this offsite link?" })
         %>
      </td>
    <% end %>
  <% end %>
  </tbody>
</table>

app/views/admin/feature_lists/_featurable_topical_events.html.erb
<table class="table table-bordered">
  <thead>
    <tr class="table-header">
      <th>Title</th>
      <th>Duration</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% featurable_topical_events.each do |event| %>
      <% next if feature_list.features.current.detect {|f| f.topical_event == event } %>
      <%= content_tag_for :tr, event do %>
        <td><%= link_to event.name, admin_topical_event_path(event) %></td>
        <td><%= l event.start_date.to_date %> to <%= l event.end_date.to_date %></td>
        <td>
          <%= link_to("Feature", polymorphic_url([:new, :admin, @feature_list, :feature], topical_event_id: event.id), class: 'btn btn-default') %>
        </td>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/admin/feature_lists/_feature_list.html.erb
<%= render partial: 'admin/feature_lists/current_feature_list', locals: {feature_list: feature_list} %>

<hr />
<h2 class="add-bottom-margin feature-title">Feature new documents</h2>
<div class="row">
  <div class="col-md-3">
    <%= render partial: 'admin/editions/filter_options', locals: { filter_by: filter_by, filter_action: polymorphic_url([:features, :admin, feature_list.featurable], locale: feature_list.locale) } %>
  </div>
  <div class="col-md-9" id="search_results">
    <%= render partial: "admin/feature_lists/search_results", locals: {feature_list: feature_list} %>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <% if @featurable_topical_events.any? %>
      <h2 class="add-bottom-margin">Feature new topical events</h2>
      <%= render partial: 'admin/feature_lists/featurable_topical_events', locals: { feature_list: feature_list, featurable_topical_events: @featurable_topical_events } %>
    <% end %>
  </div>

  <div class="col-md-6">
    <h2 class="add-bottom-margin">Feature non-GOV.UK government link</h2>
    <% if @featurable_offsite_links.any? %>
      <%= render partial: 'admin/feature_lists/featurable_offsite_links', locals: { feature_list: feature_list, featurable_offsite_links: @featurable_offsite_links } %>
    <% else %>
      <p class="no-content no-content-bordered">There are currently no non-GOV.UK government links.</p>
    <% end %>

    <% if @organisation %>
      <%= link_to "Create a non-GOV.UK government link", new_admin_organisation_offsite_link_path(@organisation), class: "btn btn-default" %>
    <% end %>

    <% if @world_location %>
      <%= link_to "Create a non-GOV.UK government link", new_admin_world_location_offsite_link_path(@world_location), class: "btn btn-default" %>
    <% end %>
  </div>
</div>

app/views/admin/feature_lists/_search_results.html.erb
<h3 class="add-bottom-margin">
  <%= @filter.page_title %>
</h3>

<%= render partial: 'admin/feature_lists/featurable_editions', locals: { feature_list: feature_list, featurable_editions: @filter.editions(feature_list.locale) } %>