config/routes.rb
    # Allow access to all routes in development, and restrict to the
    # internal or external admin host otherwise.
    !Rails.env.production? || valid_admin_host?(request.host)
  end

  def self.valid_admin_host?(host)
    [Whitehall.admin_host, Whitehall.internal_admin_host].include? host
  end
end

Whitehall::Application.routes.draw do
  VALID_LOCALES_REGEX = Regexp.compile(Locale.non_english.map(&:code).join("|"))

  def redirect(path, options = { prefix: Whitehall.router_prefix })
    super(options[:prefix] + path)
  end

  def external_redirect(path_prefix, target)
    get path_prefix => redirect(target, prefix: "")
    get "#{path_prefix}/*anything" => redirect(target, prefix: "")
  end

  root to: redirect("/admin/"), constraints: lambda { |request|
    ::Whitehall.admin_host == request.host
  }

  get "/government/ministers/minister-of-state--11" => redirect("/government/people/kris-hopkins", prefix: "")

  # This API is documented here:
  # https://github.com/alphagov/whitehall/blob/master/docs/api.md
  namespace "api" do
    resources :governments, only: %i[index show], defaults: { format: :json }
    resources :world_locations, path: "world-locations", only: %i[index show], defaults: { format: :json } do
      resources :worldwide_organisations, path: "organisations", only: [:index], defaults: { format: :json }
    end
    resources :worldwide_organisations, path: "worldwide-organisations", only: [:show], defaults: { format: :json }
  end

  # World locations and Worldwide organisations
  get "/world/organisations/:organisation_id/office" => redirect("/world/organisations/%{organisation_id}", prefix: "")
  get "/world/organisations/:organisation_id/about" => redirect("/world/organisations/%{organisation_id}", prefix: "")
  get "/world/organisations/:id(.:locale)", as: "worldwide_organisation", to: "worldwide_organisations#show", constraints: { locale: VALID_LOCALES_REGEX }

  resources :worldwide_organisations, path: "world/organisations", only: [] do
    get "/about/:id(.:locale)", as: "corporate_information_page", to: "corporate_information_pages#show", constraints: { locale: VALID_LOCALES_REGEX }
    # Dummy path for the sake of polymorphic_path: will always be directed above.
    get "/about(.:locale)", as: "about", to: "_#_", constraints: { locale: VALID_LOCALES_REGEX }

    get "/office/:id(.:locale)", to: "worldwide_offices#show", as: :worldwide_office, constraints: { locale: VALID_LOCALES_REGEX }
  end

  resources :embassies, path: "world/embassies", only: [:index]

  get "/world(.:locale)", as: "world_locations", to: "world_locations#index", constraints: { locale: VALID_LOCALES_REGEX }
  get "/world/:id(.:locale)", as: "world_location", to: "world_locations#show", constraints: { locale: VALID_LOCALES_REGEX }
  get "/world/:world_location_id/news(.:locale)", as: "world_location_news_index", to: "world_location_news#index", constraints: { locale: VALID_LOCALES_REGEX }

  scope Whitehall.router_prefix, shallow_path: Whitehall.router_prefix do
    external_redirect "/organisations/ministry-of-defence-police-and-guarding-agency",
      "http://webarchive.nationalarchives.gov.uk/20121212174735/http://www.mod.uk/DefenceInternet/AboutDefence/WhatWeDo/SecurityandIntelligence/MDPGA/"

    root to: redirect("/", prefix: ""), via: :get, as: :main_root
    get "/how-government-works" => "home#how_government_works", as: "how_government_works"
    scope "/get-involved" do
      root to: "home#get_involved", as: :get_involved, via: :get
      get "take-part" => redirect("/get-involved#take-part")

      # Controller removed. Whitehall frontend no longer serves these
      # pages however the route is needed to generate path and url
      # helper methods.
      # TODO: Remove when take part page paths can be otherwise generated
      get "take-part/:id", to: "take_part_pages#show", as: "take_part_page"
    end

    # Past foreign secretaries are currently hard-coded, so this
    # resource falls straight through to views.
    resources :past_foreign_secretaries, path: "/history/past-foreign-secretaries", only: %i[index show]
    # Past chancellors is also hard-coded
    get "history/past-chancellors" => "historic_appointments#past_chancellors"

    # Past foreign secretaries and past chancellors are here for the
    # purposes of reversing URLs in a consistent way from other views.

    # TODO: make these dynamic, they're hard-coded above.
    get "/history/:role" => "historic_appointments#index", constraints: { role: /(past-prime-ministers)|(past-chancellors)|(past-foreign-secretaries)/ }, as: "historic_appointments"
    get "/history/:role/:person_id" => "historic_appointments#show", constraints: { role: /(past-prime-ministers)|(past-chancellors)|(past-foreign-secretaries)/ }, as: "historic_appointment"
    resources :histories, path: "history", only: %i[index show]

    resource :email_signups, path: "email-signup", only: %i[new]
    get "/email-signup", to: redirect("/")

    get "/tour" => redirect("/tour", prefix: "")

    get "/announcements(.:locale)", as: "announcements", to: "announcements#index", constraints: { locale: VALID_LOCALES_REGEX }
    get "/news/:id(.:locale)", as: "news_article", to: "news_articles#show", constraints: { locale: VALID_LOCALES_REGEX }
    resources :fatality_notices, path: "fatalities", only: [:show]
    get "/news" => redirect("/announcements"), as: "news_articles"
    get "/fatalities" => redirect("/announcements"), as: "fatality_notices"

    get "/latest" => "latest#index", as: "latest"

    get "/publications(.:locale)", as: "publications", to: "publications#index", constraints: { locale: VALID_LOCALES_REGEX }
    get "/publications/:id(.:locale)", as: "publication", to: "_#_", constraints: { locale: VALID_LOCALES_REGEX }
    get "/publications/:publication_id/:id" => "_#_", as: "publication_html_attachment"

    # TODO: Remove when paths can be generated without a routes entry
    get "/case-studies/:id(.:locale)", as: "case_study", to: "case_studies#show", constraints: { locale: VALID_LOCALES_REGEX }
    get "/speeches/:id(.:locale)", as: "speech", to: "speeches#show", constraints: { locale: VALID_LOCALES_REGEX }
    resources :statistical_data_sets, path: "statistical-data-sets", only: [:show]

    get "/speeches" => redirect("/announcements")

    # Controller removed for stats announce show. Whitehall frontend no longer serves these
    # pages however the route is needed to generate path and url
    # helper methods.
    # TODO: Remove `:show` when stats announcement paths can be otherwise generated
    resources :statistics_announcements, path: "statistics/announcements", only: %i[index show]
    get "/statistics(.:locale)", as: "statistics", to: "statistics#index", constraints: { locale: VALID_LOCALES_REGEX }
    get "/statistics/:id(.:locale)", as: "statistic", to: "_#_", constraints: { locale: VALID_LOCALES_REGEX }
    get "/world-location-news(.:locale)", as: "world_location_news_articles", to: "world_location_news_articles#index", constraints: { locale: VALID_LOCALES_REGEX }
    get "/world-location-news/:id(.:locale)", as: "world_location_news_article", to: "world_location_news_articles#show", constraints: { locale: VALID_LOCALES_REGEX }

    resources :consultations, only: %i[index show] do
      collection do
        get :open
        get :closed
        get :upcoming
      end
    end
    get "/consultations/:consultation_id/:id" => "_#_", as: "consultation_html_attachment"
    get "/consultations/:consultation_id/outcome/:id" => "_#_", as: "consultation_outcome_html_attachment"
    get "/consultations/:consultation_id/public-feedback/:id" => "_#_", as: "consultation_public_feedback_html_attachment"

    resources :topics, path: "topics", only: [:show]
    resources :topical_events, path: "topical-events", only: [:show] do
      # Controller removed. Whitehall frontend no longer serves these
      # pages however the route is needed to generate path and url
      # helper methods.
      # TODO: Remove when about page paths can be otherwise generated
      resource :about_pages, path: "about", only: [:show]
    end

    # TODO: Remove when paths can be generated without a routes entry
    resources :document_collections, only: [:show], path: "collections"
    get "/collections" => redirect("/publications")

    get "/organisations/:id(.:locale)", as: "organisation", to: "organisations#show", constraints: { locale: VALID_LOCALES_REGEX }
    resources :organisations, only: [:index]

    resources :organisations, only: [] do
      # No need to forward the locale as collections aren't localised.
      get "/series/:slug(.:locale)" => redirect("/collections/%{slug}"), constraints: { locale: VALID_LOCALES_REGEX }
      get "/series(.:locale)" => redirect("/publications"), constraints: { locale: VALID_LOCALES_REGEX }
      get "/about(.:locale)", as: "corporate_information_pages", to: "corporate_information_pages#index", constraints: { locale: VALID_LOCALES_REGEX }
      get "/about/:id(.:locale)", as: "corporate_information_page", to: "corporate_information_pages#show", constraints: { locale: VALID_LOCALES_REGEX }
    end
    get "/organisations/:organisation_id/groups" => redirect("/organisations/%{organisation_id}")
    get "/organisations/:organisation_id/groups/:id" => redirect("/organisations/%{organisation_id}")
    get "/organisations/:organisation_id/consultations" => redirect("/organisations/%{organisation_id}")
    get "/organisations/:organisation_id/chiefs-of-staff" => redirect("/organisations/%{organisation_id}")
    get "/organisations/:organisation_slug/email-signup" => "email_signup_information#show",
      as: :organisation_email_signup_information

    get "/ministers(.:locale)", as: "ministerial_roles", to: "ministerial_roles#index", constraints: { locale: VALID_LOCALES_REGEX }
    get "/ministers/:id(.:locale)", as: "ministerial_role", to: "ministerial_roles#show", constraints: { locale: VALID_LOCALES_REGEX }

app/controllers/home_controller.rb
class HomeController < PublicFacingController
  layout "frontend"

  def how_government_works
    sitewide_setting = load_reshuffle_setting
    @is_during_reshuffle = sitewide_setting.on if sitewide_setting
    @prime_minister = MinisterialRole.find_by(slug: "prime-minister").current_person
    sorter = MinisterSorter.new
    @cabinet_minister_count = sorter.cabinet_ministers.count - 1 # subtract one to discount PM
    @other_minister_count = sorter.other_ministers.count
    @all_ministers_count = @cabinet_minister_count + @other_minister_count + 1 # add one to put the PM back in
    @ministerial_department_count = Organisation.listable.ministerial_departments.count
    @non_ministerial_department_count = Organisation.listable.non_ministerial_departments.count
  end

  def get_involved
    @open_consultation_count = Consultation.published.open.count
    @closed_consultation_count = Consultation.published.closed_at_or_after(1.year.ago).count
    @next_closing_consultations = decorate_collection(Consultation.published.open.order("closing_at asc").limit(1), PublicationesquePresenter)
    @recently_opened_consultations = decorate_collection(Consultation.published.open.order("opening_at desc").limit(3), PublicationesquePresenter)
    @recent_consultation_outcomes = decorate_collection(Consultation.published.closed.responded.order("closing_at desc").limit(3), PublicationesquePresenter)
    @take_part_pages = TakePartPage.in_order
  end

  def history_king_charles_street; end

  def history_lancaster_house; end
end

app/views/home/get_involved.html.erb
<% page_title "Get involved" %>
<% page_class "get-involved" %>
<% meta_description "Find out how you can engage with government directly, and take part locally, nationally or internationally." %>

<header class="block headings-block">
  <div class="inner-block floated-children">
    <%= render partial: 'shared/heading',
              locals: { big: true,
                        heading: "Get involved" } %>
    <p class="intro-paragraph">Find out how you can <a href="#engage-with-government">engage with government</a> directly, and <a href="#take-part">take&nbsp;part</a> locally, nationally or internationally.</p>
  </div>
</header>

<div class="block">
  <div class="inner-block floated-children">
    <h2 id="engage-with-government">Engage with government</h2>
    <section class="respond-to-consultations">
      <div class="head-section">
        <h3>Respond to consultations</h3>
      </div>
      <div class="column">
        <div class="content">
          <p>You can give your views on new or changing government policies by responding to consultations. Government departments take these responses into consideration before making decisions.</p>
        </div>
      </div>
    </section>
    <section class="consultations">
      <div class="head-section">
        <dl class="values">
          <dt><%= link_to @open_consultation_count, publications_filter_path(:publication_filter_option => 'open-consultations') %>
        </dt>
          <dd>Open consultations</dd>
          <dt><%=  link_to @closed_consultation_count, publications_filter_path(:publication_filter_option => 'closed-consultations') %></dt>
          <dd>Closed consultations in the past 12 months</dd>
          <% if false # this count not implemented yet %>
            <dt><a href="#">29</a></dt>
            <dd>Responses in the past 12 months</dd>
          <% end %>
        </dl>
      </div>
      <div class="consultation-lists">
        <div class="consultation-closing-soon">
          <% @next_closing_consultations.each do |consultation| %>
            <h3><%= consultation.time_until_closure %></h3>
          <% end %>
          <ol class="document-list">
            <% @next_closing_consultations.each do |consultation| %>
              <%= content_tag_for(:li, consultation, class: 'document-row') do %>
                <h3><%= consultation.title %></h3>
                <ul class="attributes">
                  <li><%= link_to "Read and respond", public_document_path(consultation) %></li>
                </ul>
              <% end %>
            <% end %>
          </ol>
        </div>
        <div>
          <div class="column">
            <div class="content">
              <h3>Recently opened</h3>
              <ol class="document-list">
                <% @recently_opened_consultations.each do |consultation| %>
                  <li class="document-row">
                    <h3><%= link_to consultation.title, public_document_path(consultation) %></h3>
                    <ul class="attributes">
                      <li><%= consultation.organisations.map(&:acronym).to_sentence %></li>
                      <li>Closes <%= consultation.date_microformat(:closing_at) %></li>
                      <li><%= link_to "Read and respond", public_document_path(consultation) %></li>
                    </ul>
                  </li>
                <% end %>
              </ol>
              <p class="see-all"><%= link_to("Search all consultations", publications_path(publication_filter_option: "consultations")) %></p>
            </div>
          </div>
          <div class="column">
            <div class="content">
              <h3>Recent outcomes</h3>
              <ol class="document-list">
                <% @recent_consultation_outcomes.each do |consultation| %>
                  <li class="document-row">
                    <h3><%= link_to consultation.title, public_document_path(consultation) %></h3>
                    <ul class="attributes">
                      <li><%= consultation.organisations.map(&:acronym).to_sentence %></li>
                      <li>Closed <%= consultation.date_microformat(:closing_at) %></li>
                      <li><%= link_to "See the outcome", public_document_path(consultation) %></li>
                    </ul>
                  </li>
                <% end %>
              </ol>
            </div>
          </div>
        </div>
      </div>
    </section>
    <hr class="keyline">
    <section class="start-a-petition">
      <div class="head-section">
        <h3>Start a petition</h3>
      </div>
      <div class="column">
        <div class="content">
          <p>You can <a href="https://petition.parliament.uk/" rel="external">create a petition</a> to influence government and Parliament. If the petition gets at least 100,000 online signatures, it will be considered for debate in the House of Commons.</p>
        </div>
      </div>
    </section>
    <hr class="keyline">
    <section class="comment-follow">
      <div class="head-section">
        <h3>Follow a blog or social media channel</h3>
      </div>
      <div class="column">
        <div class="content">
          <p>For an instant way to interact with government departments, try their social media streams. These are listed under 'Follow us' on the department's home page. As well as access to blogs, audio, video and more, you can comment, debate and rate.</p>
          <p class="see-all"><a href="/government/organisations/">See all government departments</a></p>
          <p>Some active government blogs include:</p>
          <ul class="index-list">
            <li><a href="https://history.blog.gov.uk" rel="external">History of Government</a></li>
            <li><a href="https://quarterly.blog.gov.uk" rel="external">Civil Service Quarterly</a></li>
            <li><a href="http://blogs.fco.gov.uk" rel="external">FCO bloggers</a></li>
            <li><a href="https://gds.blog.gov.uk/" rel="external">Government Digital Service</a></li>
            <li><a href="https://civilservice.blog.gov.uk/author/sir-jeremy-heywood/" rel="external">Head of the Civil Service</a></li>
          </ul>
        </div>
      </div>
    </section>
  </div>
</div>


<div class="block">
  <div class="inner-block floated-children featured-news">
    <h2 id="take-part">Take part</h2>
    <section class="take-part-pages">
      <% @take_part_pages.each_with_index do |take_part_page, index| %>
        <article<% if index % 3 == 0 %> class="article-clear"<% end %>>
          <div class="content">
            <span class="image-holder">
              <%= link_to image_tag(take_part_page.image_url(:s300), alt: take_part_page.image_alt_text), take_part_page, title: take_part_page.title, class: 'img' %>
            </span>
            <div class="text">
              <h3><%= link_to take_part_page.title, take_part_page %></h3>
              <p class="summary"><%= format_with_html_line_breaks(take_part_page.summary) %></p>
            </div>
          </div>
        </article>
      <% end %>
    </section>
    <hr class="keyline">
    <section class="more-ways">
      <div class="head-section">
        <h3>More ways to take part</h3>
      </div>
      <div class="column">
        <div class="content">
          <p>Many people are already volunteering, donating and contributing, both in the UK and abroad. If you&rsquo;d like to join them, but don&rsquo;t know where to start, here&rsquo;s a list of suggestions:</p>
          <ul class="index-list">
            <li><a href="http://www.volunteerics.org/" rel="external">Join the International Citizen Service (18- to 25-year-olds)</a></li>
            <li><a href="http://www.ourwatch.org.uk/knowledge-base-category/how-to-get-involved/" rel="external">Take part in your local Neighbourhood Watch</a></li>
            <li><a href="/donating-to-charity">Make a donation to charity</a></li>
            <li><a href="https://schoolsonline.britishcouncil.org/about-schools-online/about-programmes/connecting-classrooms" rel="external">Link up with a school overseas</a></li>
          </ul>
        </div>
      </div>
    </section>
  </div>
</div>